### ISSUE TITLE
Can't import the package

### ISSUE THREAD

**Issue by albertmonzo** [Ernyoke/Imger#2]
Trying to import like this

```go
        "github.com/ernyoke/imger/grayscale"
	"github.com/ernyoke/imger/threshold"
```

and `go get -u github.com/ernyoke/imger/grayscale` and `go get -u github.com/ernyoke/imger/threshold` 

Somehow grayscale imports fine, but then I get 

```
go: finding module for package github.com/ernyoke/imger/threshold
github.com/monzo/wearedev/service.cheque-image-processor/domain imports
        github.com/ernyoke/imger/threshold: module github.com/ernyoke/imger@latest found (v0.1.0), but does not contain package github.com/ernyoke/imger/threshold
```

Note the capitalisation `ernyoke/imger`, as otherwise
```
 go get github.com/Ernyoke/Imger             
go: github.com/Ernyoke/Imger@v0.1.0: parsing go.mod:
        module declares its path as: github.com/ernyoke/imger
                but was required as: github.com/Ernyoke/Imger
```

I was able to work around this with 

```
go get github.com/Ernyoke/Imger@55700becd332
```

**Comment by Ernyoke** [comment]
Hi Albert,

Thank you for reporting this issue. 

I suggest you should use `go get -u github.com/ernyoke/imger@v1.0.0". The golang cache from google had an erroneous version of this project for version numbers bellow `1.0.0`.

Let me know if there are other issues you are facing.

Apologies for the late response,

Ervin
